title: Basic GIT workflow
author: A. Maslowski
email: anthony.maslowski@gmail.com
description: > # this means to ignore newlines until "baseurl:"  
  Basic GIT workflow notes as an exercise to learn GIT

# social links
twitter_username: @amaslows
github_username: @amaslows

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-merlot
